name: pre-submit e2e docker-based default

on:
  pull_request:
    branches: [main]
  merge_group:
  workflow_dispatch:

permissions: read-all

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    permissions:
      id-token: write # For signing.
      contents: write # For asset uploads.
      actions: read # For reading workflow info.
    uses: ./.github/workflows/builder_docker-based_slsa3.yml
    with:
      builder-image: "bash"
      builder-digest: "sha256:9e2ba52487d945504d250de186cb4fe2e3ba023ed2921dd6ac8b97ed43e76af9"
      config-path: "internal/builders/docker/testdata/wildcard-config.toml"
      provenance-name: "attestation.intoto"
      compile-builder: true

  verify:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - uses: actions/download-artifact@e9ef242655d12993efdcda9058dee2db83a2cb9b
        with:
          name: ${{ needs.build.outputs.build-outputs-name }}
          path: outputs
      - name: Get build artifact
        id: build
        run: |
          name=$(find outputs/ -type f | head -1)
          cp $name .
          echo "name=$name" >> $GITHUB_OUTPUT
      - uses: actions/download-artifact@e9ef242655d12993efdcda9058dee2db83a2cb9b
        with:
          name: ${{ needs.build.outputs.attestations-download-name }}
      - run: ./.github/workflows/scripts/pre-submit.e2e.docker-based.default.sh