name: Builders releaser

on:
  # For manual tests.
  workflow_dispatch:
    inputs:
      release-tag:
        description: "Release tag to test"
        required: true
        type: string
  push:
    tags:
      - "*" # triggers only if push new tag version, like `0.8.4` or else

permissions: read-all

jobs:
  # Pre-release reference verification.
  pre-release-refs:
    name: pre release refs verification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          path: __THIS_REPO__
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          repository: slsa-framework/example-package
          ref: main
          path: __EXAMPLE_PACKAGE__
      - name: manual release ref
        env:
          RELEASE_TAG: "${{ inputs.release-tag }}"
        if: github.ref_type != 'tag'
        run: ./__THIS_REPO__/.github/workflows/scripts/pre-release/references.sh
      - name: new tag release ref
        env:
          RELEASE_TAG: "${{ github.ref_name }}"
        if: github.ref_type == 'tag'
        run: ./__THIS_REPO__/.github/workflows/scripts/pre-release/references.sh

  # Generic generator.
  container-generator:
    needs: [pre-release-refs]
    permissions:
      id-token: write # For signing.
      contents: write # For asset uploads.
      actions: read # For the entrypoint.
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v1.6.0-rc.3
    with:
      go-version: "1.20"
      config-file: .github/workflows/configs-container/config-release.yml
      compile-builder: true

  # Generic generator.
  generic-generator:
    needs: [pre-release-refs]
    permissions:
      id-token: write # For signing.
      contents: write # For asset uploads.
      actions: read # For the entrypoint.
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v1.6.0-rc.3
    with:
      go-version: "1.20"
      config-file: .github/workflows/configs-generic/config-release.yml
      compile-builder: true

  # Go builder.
  go-builder:
    needs: [pre-release-refs]
    permissions:
      id-token: write # For signing.
      contents: write # For asset uploads.
      actions: read # For the entrypoint.
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v1.6.0-rc.3
    with:
      go-version: "1.20"
      config-file: .github/workflows/configs-go/config-release.yml
      compile-builder: true

  # Docker-based builder.
  docker-builder:
    needs: [pre-release-refs]
    permissions:
      id-token: write # For signing.
      contents: write # For asset uploads.
      actions: read # For the entrypoint.
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v1.6.0-rc.3
    with:
      go-version: "1.20"
      config-file: .github/workflows/configs-docker/config-release.yml
      compile-builder: true
