# Copyright 2022 SLSA Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: SLSA provenance generator

permissions:
  contents: read

###################################################################
#                                                                 #
#            Input and output argument definitions                #
#                                                                 #
###################################################################
on:
  workflow_call:
    inputs:
      subjects:
        description: "Artifacts for which to generate provenance, formatted the same as the output of sha256sum (SHA256 NAME\\n[...])"
        required: true
        type: string
    outputs:
      attestation-name:
        description: "The artifact name of the signed provenance"
        value: ${{ jobs.generator.outputs.signed-provenance-name }}

jobs:
  # TODO: Use detect-workflow when #125 is merged.
  # detect-env:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     id-token: write # Needed to detect the current reusable repository and ref.
  #     contents: read
  #   outputs:
  #     repository: ${{ steps.detect.outputs.repository }}
  #     ref: ${{ steps.detect.outputs.ref }}
  #   steps:
  #     - name: Detect the repository and ref
  #       id: detect
  #       uses: slsa-framework/slsa-github-generator/.github/actions/detect-workflow@aec5cd1e20507a6f1b5d8e82a8f62c3e2ca9b9f9
  detect-env:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed to detect the current reusable repository and ref.
      contents: read
    outputs:
      builder_repo: ${{ steps.detect.outputs.repository }}
      builder_ref: ${{ steps.detect.outputs.ref }}
    steps:
      - name: Detect the builder ref
        id: detect
        env:
          PULL_REQUEST_REPOSITORY: "${{ github.event.pull_request.head.repo.full_name }}"
        shell: bash
        run: |
          # On pull requests, permissions are not available.
          if [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
              echo "::set-output name=builder_repo::$PULL_REQUEST_REPOSITORY"
              echo "::set-output name=builder_ref::$GITHUB_HEAD_REF"
              exit 0
          fi

          if [[ -z "$ACTIONS_ID_TOKEN_REQUEST_TOKEN" ]] || [[ -z "$ACTIONS_ID_TOKEN_REQUEST_URL" ]]; then
              echo "OIDC not available" not available.
              exit 1
          fi

          status_code=$(curl -sS -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=$GITHUB_REPOSITORY/builder" -o jwt.json -w '%{http_code}')
          if [[ $status_code -ge 400 ]]; then
              error_msg=$(jq -r .message jwt.json 2>/dev/null || echo 'unknown error')
              echo "Failed to get OIDC token from GitHub, response $status_code: $error_msg"
              exit 2;
          fi

          export WORKFLOW_REF=$(cat jwt.json | jq -r '.value' | cut -d "." -f2 | base64 -d | jq -r '.job_workflow_ref')
          if [ -z $WORKFLOW_REF ]; then
              echo "OIDC token parsing failure: job_workflow_ref could not be retrieved"
              exit 3;
          fi

          echo "::set-output name=repository::$(echo $WORKFLOW_REF | cut -d "@" -f1 | cut -d '/' -f1-2)"
          echo "::set-output name=ref::$(echo $WORKFLOW_REF | cut -d "@" -f2)"

  ###################################################################
  #                                                                 #
  #                       Build the generator                       #
  #                                                                 #
  ###################################################################
  generator:
    outputs:
      signed-provenance-name: ${{ steps.sign-prov.outputs.signed-provenance-name }}
    runs-on: ubuntu-latest
    needs: [detect-env]
    permissions:
      id-token: write # Needed for keyless.
      contents: read
      # actions permissions are needed to read info on the workflow and
      # workflow run.
      actions: read
    steps:
      - name: Checkout the repository
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.3.4
        with:
          fetch-depth: 0
          repository: "${{ needs.detect-env.outputs.repository }}"
          ref: "${{ needs.detect-env.outputs.ref }}"

      - name: Set up golang environment
        uses: actions/setup-go@424fc82d43fa5a37540bae62709ddcc23d9520d4 # v2.1.3
        with:
          go-version: 1.18

      - name: Download dependencies
        shell: bash
        run: |
          set -euo pipefail
          #TODO(reproducible)
          go mod vendor

      # TODO(hermeticity) OS-level.

      - name: Build slsa-github-generator
        shell: bash
        id: generator-gen
        run: |
          set -euo pipefail

          # https://go.dev/ref/mod#build-commands.
          go build -mod=vendor -o builder github.com/slsa-framework/slsa-github-generator/internal/builders/generic
          chmod a+x builder

      - name: Create and sign provenance
        id: sign-prov
        shell: bash
        # NOTE: Inputs and github context are set to environment variables in
        # order to avoid script injection.
        # See: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#understanding-the-risk-of-script-injections
        env:
          SUBJECTS: "${{ inputs.subjects }}"
          GITHUB_CONTEXT: "${{ toJSON(github) }}"
        run: |
          set -euo pipefail
          # Create and sign provenance
          # This sets signed-provenance-name to the name of the signed DSSE envelope.
          ./builder attest --subjects "${SUBJECTS}" -g attestation.intoto.jsonl
          echo "::set-output name=signed-provenance-name::attestation.intoto.jsonl"

      - name: Upload the signed provenance
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
        with:
          name: "${{ steps.sign-prov.outputs.signed-provenance-name }}"
          path: "${{ steps.sign-prov.outputs.signed-provenance-name }}"
          if-no-files-found: error
          retention-days: 5
